language: java
sudo: false

cache:
  directories:
  - "$HOME/.beast"
before_cache:
  - rm -rf $HOME/.beast/*

before_install:
    - wget https://github.com/CompEvol/beast2/releases/download/v2.5.0/BEAST.v2.5.0.Linux.tgz
    - tar zxvf *.tgz 
    - BEAST_LIB="./lib"
    - ls "$BEAST_LIB"      

jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    
    script:
    - pwd
    - ls . 
    - ls $HOME/.beast     
    - java -Djava.library.path="$BEAST_LIB" -Duser.language=en -cp "$BEAST_LIB/beast.jar" beast.util.PackageManager -updatenow SSM -dir "$HOME/.beast/"
    - ls $HOME/.beast
    after_success:
    - jar xf $HOME/.beast/SSM/*.src.jar


#  - stage: deploy
#    jdk: oraclejdk8
#    script:
#    - "./continuous-deployment/before-deploy.sh"
#    - "./continuous-deployment/deploy.sh"
#    - "./continuous-deployment/upload-api-docs.sh"
#    on:
#      repo: walterxie/beast2-site
