language: java
sudo: false

cache:
  directories:
  - "$HOME/.beast"
#before_cache:
#  - rm -rf $HOME/.beast/*

before_install:
    - wget https://github.com/CompEvol/beast2/releases/download/v2.5.0/BEAST.v2.5.0.Linux.tgz
    - tar zxvf *.tgz 
    - BEAST_LIB="beast/lib"
    - ls "$BEAST_LIB"      

jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    
    script:
    - pwd
    - ls $HOME/.beast     
    - java -Djava.library.path="$BEAST_LIB" -Duser.language=en -cp "$BEAST_LIB/beast.jar" beast.util.PackageManager -add SSM -dir "$HOME/.beast"
    - java -Djava.library.path="$BEAST_LIB" -Duser.language=en -cp "$BEAST_LIB/beast.jar" beast.util.PackageManager -add Mascot -dir "$HOME/.beast"
    - ls $HOME/.beast
    after_success:
    - cd $HOME/.beast/SSM
    - jar xf *.src.jar
    - find . -type f 
    - cd $HOME/.beast/SSM
    - jar xf *.src.jar
    - find . -type f 

#  - stage: deploy
#    jdk: oraclejdk8
#    script:
#    - "./continuous-deployment/before-deploy.sh"
#    - "./continuous-deployment/deploy.sh"
#    - "./continuous-deployment/upload-api-docs.sh"
#    on:
#      repo: walterxie/beast2-site
